### ISSUE TITLE
[TODO] 해야할 일

### ISSUE THREAD

**Issue by DohyunYoun** [TikitakaDiary/MemoryTrace-Android#53]
- [ ] diaryList 페이징 처리
- [ ] 페이징 처리 통일화
- [ ] color 처리 모듈화
- [ ] 일기작성시 갤러리 권한 - contentProvider처리(섬네일 x)
- [ ] 메모리 릭
- [ ] statusInterceptor
